const QUESTION_JSON_DATA = {
  A: {
    1: { Question: "對大的聲音似乎沒反應", Element: ["1"], Token: 2 },
    2: {
      Question: "在兩到三個月個大，眼睛不會跟隨著移動的物體",
      Element: ["16"],
      Token: 100000,
    },
    3: { Question: "在三個月時拳頭握緊無法張開", Element: ["17"], Token: 4 },
    4: { Question: "在三個月時還不會抓、握物體", Element: ["7"], Token: 5 },
    5: {
      Question: "在三到四個月大，不會牙牙學語",
      Element: ["20"],
      Token: 0,
    },
    6: {
      Question: "在三個月時，對於每個方向移動單眼或雙眼有困難",
      Element: ["16"],
      Token: 1,
    },
    7: {
      Question: "在四個月大，無法拿取東西到嘴巴",
      Element: ["11"],
      Token: 3,
    },
    8: {
      Question: "在四個月的時候，沒有辦法將頭轉向聲音的發源地",
      Element: ["1"],
      Token: 2,
    },
    9: {
      Question: "在四個月的時候，身體軟趴趴的，像個用碎布做成的玩偶",
      Element: ["17"],
      Token: 4,
    },
    10: {
      Question: "在四個月的時候，身體非常僵硬有著很緊的肌肉",
      Element: ["17"],
      Token: 4,
    },
    11: {
      Question: "在六、七個月的時候，無法主動伸手去取物品T",
      Element: ["11"],
      Token: 3,
    },
    12: {
      Question: "在七個月的時候，眼珠子無法隨著近距離的物品而轉動",
      Element: ["16"],
      Token: 1,
    },
    13: {
      Question: "在七個月的時候，在活動的過程中無法集中注意力",
      Element: ["26"],
      Token: 6,
    },
  },
  B: {
    1: { Question: "拒絕被擁抱", Element: ["3"], Token: 2 },
    2: { Question: "對於周圍的聲音沒有任何的反應", Element: ["1"], Token: 2 },
    3: {
      Question: "持續地掉眼淚、淚水在眼框中打轉或對光線很敏感",
      Element: ["2"],
      Token: 2,
    },
    4: { Question: "將食物進嘴巴裡是有困難的", Element: ["11"], Token: 2 },
    5: { Question: "不會模仿玩躲貓貓", Element: ["19"], Token: 2 },
    6: { Question: "不會伸手拿別人給他的東西", Element: ["14"], Token: 2 },
    7: { Question: "不會模仿大人做拍手動作", Element: ["21"], Token: 2 },
    8: { Question: "無法學習手勢像是揮手或握手", Element: ["21"], Token: 2 },
    9: {
      Question: "在八個月的時候，無法發出模糊不清的聲音",
      Element: ["20"],
      Token: 2,
    },
    10: {
      Question: "無法在指示下把插棒放入插洞板中",
      Element: ["11"],
      Token: 2,
    },
    11: {
      Question: "即使看到某一樣物品被藏起來還是不會去尋找",
      Element: ["19"],
      Token: 2,
    },
    12: {
      Question: "無法說出單一個名詞像是爸爸媽媽",
      Element: ["20"],
      Token: 2,
    },
    13: {
      Question: "不會搖手中的玩具，使之發出聲音",
      Element: ["22"],
      Token: 2,
    },
    14: { Question: "不會自己拿奶瓶喝牛奶", Element: ["11"], Token: 2 },
  },
  C: {
    1: { Question: "TXT", Element: "1" },
    2: { Question: "TXT", Element: "1" },
    3: { Question: "TXT", Element: "1" },
    4: { Question: "TXT", Element: "1" },
    5: { Question: "TXT", Element: "1" },
    6: { Question: "TXT", Element: "1" },
    7: { Question: "TXT", Element: "1" },
    8: { Question: "TXT", Element: "1" },
    9: { Question: "TXT", Element: "1" },
    10: { Question: "TXT", Element: "1" },
    11: { Question: "TXT", Element: "1" },
    12: { Question: "TXT", Element: "1" },
    13: { Question: "TXT", Element: "1" },
  },
  D: [
    {
      1: { Question: "TXT", Element: "1" },
      2: { Question: "TXT", Element: "1" },
      3: { Question: "TXT", Element: "1" },
      4: { Question: "TXT", Element: "1" },
      5: { Question: "TXT", Element: "1" },
      6: { Question: "TXT", Element: "1" },
      7: { Question: "TXT", Element: "1" },
      8: { Question: "TXT", Element: "1" },
      9: { Question: "TXT", Element: "1" },
      10: { Question: "TXT", Element: "1" },
      11: { Question: "TXT", Element: "1" },
      12: { Question: "TXT", Element: "1" },
      13: { Question: "TXT", Element: "1" },
      14: { Question: "TXT", Element: "1" },
      15: { Question: "TXT", Element: "1" },
      16: { Question: "TXT", Element: "1" },
      17: { Question: "TXT", Element: "1" },
      18: { Question: "TXT", Element: "1" },
      19: { Question: "TXT", Element: "1" },
      20: { Question: "TXT", Element: "1" },
      21: { Question: "TXT", Element: "1" },
      22: { Question: "TXT", Element: "1" },
    },
  ],
  E: {
    1: { Question: "TXT", Element: "1" },
    2: { Question: "TXT", Element: "1" },
    3: { Question: "TXT", Element: "1" },
    4: { Question: "TXT", Element: "1" },
    5: { Question: "TXT", Element: "1" },
    6: { Question: "TXT", Element: "1" },
    7: { Question: "TXT", Element: "1" },
    8: { Question: "TXT", Element: "1" },
    9: { Question: "TXT", Element: "1" },
    10: { Question: "TXT", Element: "1" },
    11: { Question: "TXT", Element: "1" },
    12: { Question: "TXT", Element: "1" },
    13: { Question: "TXT", Element: "1" },
    14: { Question: "TXT", Element: "1" },
    15: { Question: "TXT", Element: "1" },
  },

  F: {
    1: { Question: "TXT", Element: "1" },
    2: { Question: "TXT", Element: "1" },
    3: { Question: "TXT", Element: "1" },
    4: { Question: "TXT", Element: "1" },
    5: { Question: "TXT", Element: "1" },
    6: { Question: "TXT", Element: "1" },
    7: { Question: "TXT", Element: "1" },
    8: { Question: "TXT", Element: "1" },
    9: { Question: "TXT", Element: "1" },
    10: { Question: "TXT", Element: "1" },
    11: { Question: "TXT", Element: "1" },
    12: { Question: "TXT", Element: "1" },
    13: { Question: "TXT", Element: "1" },
    14: { Question: "TXT", Element: "1" },
    15: { Question: "TXT", Element: "1" },
    16: { Question: "TXT", Element: "1" },
    17: { Question: "TXT", Element: "1" },
  },
};

export default QUESTION_JSON_DATA;
